# Generated by Django 4.0.4 on 2022-05-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='applicant_id',
            new_name='applicant_cv_id',
        ),
    ]
