# Generated by Django 4.0.4 on 2022-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='organization_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
