# Generated by Django 4.0.4 on 2022-05-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_api', '0005_alter_applicant_cv_id_alter_applicant_document_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_start_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='orgnization_id',
        ),
        migrations.AddField(
            model_name='job',
            name='orgnization_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.FileField(default='', max_length=1000, upload_to=''),
        ),
    ]
